INSERT INTO cursos (area, instituicao, curso, valor, duracao, possui_certificacao, url) VALUES
	('Programação', 'Eu Capacito', 'Diversos', 'Gratuitos', 'a partir de 20h', 'Sim', 'https://eucapacito.com.br/pesquisa-cursos'),
	('Programação', 'DIO', 'Diversos', 'Gratuitos e Pagos', 'a partir de 2h', 'Sim', 'https://www.dio.me/catalog'),
	('Programação', 'Soul Code', 'Bootcamps', 'Gratuitos e Pagos', 'a partir de 200h', 'Sim', 'https://soulcode.com/'),
	('Programação', 'Curso em vídeo', 'Diversos', 'Gratuitos', 'a partir de 8h', 'Não', 'https://www.youtube.com/@CursoemVideo/featured'),
	('Programação', 'Loiane', 'Back-and', 'Gratuitos', 'a partir de 23h', 'Sim', 'https://loiane.training/cursos'),
	('Programação', 'Soft Blue', 'Diversos', 'Gratuitos e Pagos', 'a partir de 8h', 'Sim', 'https://www.softblue.com.br/site/index#'),
	('Programação', 'Tim Tec', 'Diversos', 'Gratuitos', 'a partir de 10h', 'Sim', 'https://cursos.timtec.com.br/courses'),
	('Programação', 'Udemy', 'Diversos', 'Pagos (em média R$ 35,00)', 'a partir de 6h', 'Sim', 'https://www.udemy.com/courses/development/'),
	('Programação', 'Cel Lep', 'Python ', 'Pago (R$ 149,90)', '32h', 'Sim', 'https://br.cellep.com/tech/python-logica-de-programacao-e-poo/'),
	('Programação', 'You Tube - Rafaella Ballerini', 'Git e Git Hub', 'Gratuitos', '2h', 'Não', 'https://www.youtube.com/watch?v=UBAX-13g8OM&list=PLhkO7OMKgT_rqwGYldqcFxyN4yjFgmDh8'),
	('Programação', 'Vue.js Brasil', 'Framework JavaScript', 'Gratuito', 'indefinido', 'Sim', 'https://igorhalfeld.teachable.com/p/treinamento-completo-e-gratuito-de-vue-js-3-do-iniciante-ao-avancado'),
	('Programação', 'Programaria', 'Diversos', 'Gratuitos e Pagos', 'a partir de 2h', 'Sim', 'https://www.programaria.org/curso-online-euprogramo/'),
	('Programação', 'Potência Tech', 'Diversos', 'Gratuitos', 'a partir de 3h', 'Sim', 'https://plataforma.potenciatech.com.br/potenciatech/catalogo?institution=potenciatech'),
	('Programação', 'Geração Crescer', 'Diversos', 'Gratuitos', 'a partir de 5h', 'Sim', 'https://geracaocrescer.org.br/web/cursos/'),
	('Programação', 'AWS', 'Diversos', 'Gratuitos e Pagos', 'a partir de 1h', 'Sim', 'https://explore.skillbuilder.aws/learn/external-ecommerce;view=none?ctldoc-catalog-0=l-_%22pt-br%22'),
	('Programação', 'Instituto Porto ', 'Desenvolvimento de sistemas', 'Gratuito', '243h', 'Sim', 'https://institutoportoseguro.com.br/cursos-profissionalizantes/desenvolvedor-de-sistemas'),
	('Programação', '42 São Paulo', 'Engenharia de Softwere', 'Gratuito', 'indefinido', 'Sim', 'https://euquero.42sp.org.br/?gclid=Cj0KCQjwla-hBhD7ARIsAM9tQKv6zZJBYFzbYCszUmUhraEImZOvNgtpXZ1fHNo1iFnTvsDiBAtQsLYaAmIMEALw_wcB'),
	('Programação', 'WR Educacional', 'Diversos', 'Gratuitos', 'indefinido', 'Sim, porem pago', 'https://www.wreducacional.com.br/lista-de-cursos/programacao'),
	('Programação', 'School of Net', 'Diversos', 'Gratuitos ou plano de R$ 54,90', 'a partir de 3h', 'Sim, porem pago', 'https://www.schoolofnet.com/cursos/gratuitos'),
	('Programação', 'Prime Cursos', 'Diversos', 'Gratuitos', 'a partir de 30h', 'Sim, porém pago', 'https://www.primecursos.com.br/programacao/'),
	('UX e UI Design', 'FIAP', 'UX e Design Thinking', 'Gratuito', '40h', 'Sim', 'https://www.fiap.com.br/2022/06/06/fiap-disponibilza-20-cursos-gratuitos-nas-areas-de-tecnologia-e-negocios/'),
	('UX e UI Design', 'CollabDesign', 'Design', 'Gratuito', '36h', 'Sim', 'https://www.sympla.com.br/play/design-e-para-todos-curso-intensivo-de-design-visual-grafico/1090448'),
	('UX e UI Design', 'IPED', 'Design e Animação', 'Gratuito', 'a partir de 10h', 'Sim', 'https://www.iped.com.br/cursos-gratis/animacoes-e-design'),
	('UX e UI Design', 'Senac', 'Computação gráfica - Técnico', 'Gratuito', '1000 horas', 'Sim', 'https://www.sp.senac.br/cursos-tecnicos/curso-tecnico-em-computacao-grafica?bolsa=true'),
	('UX e UI Design', 'Tim Tec', 'UX e UI Design', 'Gratuito', '', 'Sim', 'https://cursos.timtec.com.br/course/ux-e-ui-design/intro'),
	('UX e UI Design', 'Udemy', 'Diversos', 'Pagos (em média R$ 35,00)', 'a partir de 6h', 'Sim', 'https://www.udemy.com/courses/design/'),
	('UX e UI Design', 'Udacity', 'Product Design', 'Gratuito', '2 meses', 'Sim', 'https://www.udacity.com/course/product-design--ud509'),
	('UX e UI Design', 'Canal Valor', 'Cultura ágil e Design', 'Gratuitos e pagos (em média R$ 97,00)', 'a partir de 6h', 'Sim', 'https://canalvalor.com/cursos/'),
	('Finanças e Carreira', 'Mackenzie', 'Diversos', 'Gratuitos', 'a partir de 10h', 'Sim', 'https://eadcursoslivres.mackenzie.br'),
	('Finanças e Carreira', 'IPED', 'Diversos', 'Gratuitos', 'a partir de 10h', 'Sim', 'https://www.iped.com.br/cursos-gratis/administracao'),
	('Finanças e Carreira', 'Senac', 'Diversos - Livres e Técnicos', 'Gratuitos', 'a partir de 40h', 'Sim', 'https://www.sp.senac.br/bolsas-de-estudo'),
	('Finanças e Carreira', 'Fundação Bradesco', 'Diversos', 'Gratuitos', 'a partir de 1h', 'Sim', 'https://www.ev.org.br/cursos'),
	('Finanças e Carreira', 'Tim Tec ', 'Educação Financeira', 'Gratuito', 'indefinido', 'Sim', 'https://cursos.timtec.com.br/course/c6-programa-educacao-financeira/intro'),
	('Finanças e Carreira', 'C6 Institute', 'Carreira, Finanças e Tecnologia', 'Gratuitos', 'indefinido', 'Sim', 'https://www.idea9.com.br/index.php'),
	('Finanças e Carreira', 'Coursera', 'Diversos', 'Gratuitos e pagos', 'a partir de 6h', 'Sim, porém pago', 'https://www.coursera.org/courses?query=free'),
	('Finanças e Carreira', 'Santander Becas', 'Diversos', 'Gratuitos', 'semestral', 'Sim e internacional', 'https://app.becas-santander.com/es/program/search?category=SKILLS&status=open'),
	('Finanças e Carreira', 'edX', 'Diversos', 'Gratuitos e pagos', 'a partir de 2h', 'Sim e internacional', 'https://www.edx.org/search?tab=course'),
	('Finanças e Carreira', 'Pulses Academy', 'Diversos', 'Gratuitos', 'a partir de 2h', 'Sim', 'https://pulses-academy.teachable.com/courses'),
	('Inglês', 'Senac', 'Diversos', 'Gratuitos', 'a partir de 14h', 'Sim', 'https://www.sp.senac.br/busca?q=ingl%C3%AAs&tipo-curso=40413#c'),
	('Inglês', 'Santander Becas', 'Diversos', 'Gratuitos', 'semestral', 'Sim e internacional', 'https://app.becas-santander.com/es/program/search?category=LANGUAGE&status=open'),
	('Inglês', 'Geração Crescer', 'Inglês Básico', 'Gratuito', '', 'Sim', 'https://geracaocrescer.org.br/web/cursos/'),
	('Webinars e Eventos', 'EBAC', 'Diversos', 'Gratuitos', 'a partir de 10h', 'Sim', 'https://ebaconline.com.br/webinars'),
	('Webinars e Eventos', 'Google I/O', 'Diversos', 'Gratuitos', 'a partir de 3h', '', 'https://io.google/2021/program/content/?4=topic_design&lng=pt-BR'),
	('Webinars, Eventos e Conteúdos', 'Cubos Academy', 'Diversos', 'Gratuitos', 'a partir de 1h', 'Não', 'https://cubos.academy/conteudos-gratuitos'),
	('Webinars e Eventos', 'How Edu', 'Diversos', 'Gratuitos', 'a partir de 1h', 'Não', 'https://howedu.com.br/nossos-eventos/'),
	('Tutoriais e conteudos', 'W3Schools', 'Diversos em Programação', 'Gratuitos', 'indefinido', 'Sim, porém pago', 'https://www.w3schools.com/default.asp'),
	('Conteudos', 'Mergo', 'Diversos em UX-UI Design', 'Gratuitos', 'indefinido', 'Não', 'https://uxdesign.blog.br/estudos-ux/home'),
	('Conteudos', 'Etalent', 'Diversos sobre carreira', 'Gratuitos', 'indefinido', 'Não', 'https://etalent.com.br/artigos/autoconhecimento-carreira-e-sucesso/soft-skills-carreira/'),
	('Dicas de cursos', 'Tech tudo', '6 dicas', ' Gratuitos', 'indefinido', 'Sim', 'https://www.techtudo.com.br/listas/2022/07/curso-de-programacao-para-iniciantes-6-sites-para-aprender-a-programar.ghtml'),
	('Dicas de cursos', 'hostinger', '25 dicas', 'Gratuitos', 'indefinido', 'Sim', 'https://www.hostinger.com.br/tutoriais/11-sites-aprender-como-programar-de-graca');